/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ConnectionSQL;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.Main;

/**
 *
 * @author LinhDzai
 */
public class LoginSQLServer extends javax.swing.JFrame {
    ConnectionSQL c = new ConnectionSQL();
    public Connection con = ConnectionSQL.getConnection();
    /**
     * Creates new form LoginSQLServer
     */
    public LoginSQLServer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUserN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPw = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(255, 0, 51));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 48, 93));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Administrator-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 103, 59, 57));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/preferences-desktop-user-password-icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 168, 59, 57));

        jTextFieldUserN.setBackground(new java.awt.Color(31, 48, 93));
        jTextFieldUserN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldUserN.setForeground(new java.awt.Color(102, 255, 204));
        jTextFieldUserN.setText("User name");
        jTextFieldUserN.setBorder(null);
        jTextFieldUserN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUserNMouseClicked(evt);
            }
        });
        jPanel1.add(jTextFieldUserN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, -1));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO SQL TOOLS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 283, 63));

        jTextFieldPw.setBackground(new java.awt.Color(31, 48, 93));
        jTextFieldPw.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldPw.setForeground(new java.awt.Color(102, 255, 204));
        jTextFieldPw.setText("Password");
        jTextFieldPw.setBorder(null);
        jTextFieldPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPwMouseClicked(evt);
            }
        });
        jTextFieldPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPwActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 173, -1));

        jButton1.setBackground(new java.awt.Color(31, 48, 93));
        jButton1.setForeground(new java.awt.Color(102, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Check-icon.png"))); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 243, 96, 34));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 152, 190, 10));

        jButtonExit.setBackground(new java.awt.Color(153, 255, 255));
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close-icon.png"))); // NOI18N
        jButtonExit.setBorder(null);
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExitMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPwActionPerformed

    private void jTextFieldUserNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUserNMouseClicked
        jTextFieldUserN.setText("");
    }//GEN-LAST:event_jTextFieldUserNMouseClicked

    private void jTextFieldPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPwMouseClicked
       jTextFieldPw.setText("");
    }//GEN-LAST:event_jTextFieldPwMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        checkLogin();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMouseClicked
    public void checkLogin(){
        if((!jTextFieldPw.getText().equals("2301")) || (!jTextFieldUserN.getText().equals("sa")))
            JOptionPane.showMessageDialog(rootPane,"USER OR PASSWORD NOT CORRECT!");
        else
            callMain();
    }
    public void callMain() {
        Main m = new Main();
        m.setVisible(true);
        m.pack();
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSQLServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSQLServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSQLServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSQLServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSQLServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldPw;
    private javax.swing.JTextField jTextFieldUserN;
    // End of variables declaration//GEN-END:variables
}
