/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Controller;
import control.Controllerv2;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DataBase;
import model.InfoBasicDB;
import java.lang.String;

/**
 *
 * @author LinhDzai
 */
public class Main extends javax.swing.JFrame {

    int x, y;
    Controller con = new Controller();
    ArrayList<DataBase> listdb;
    ArrayList<InfoBasicDB> listIf;
    DefaultTableModel model;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.MAGENTA));
        model = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonDrop = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDone = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonExport = new javax.swing.JButton();
        jButtonScan = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldNameDB = new javax.swing.JTextField();
        jTextFieldNameTB = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 0, 51));
        setBounds(new java.awt.Rectangle(500, 500, 20, 20));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);
        setIconImages(null);
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(40, 40, 40, 40));
        setMaximumSize(new java.awt.Dimension(940, 450));
        setUndecorated(true);
        setSize(new java.awt.Dimension(840, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Cloud-Minus-icon.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\User-icon.png")); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 30, 40));

        jLabel3.setText("linhcopper@gmail.com");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 130, -1));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 130, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Files-Sql-icon.png")); // NOI18N
        jLabel4.setText("SQLSERVER TOOLS");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 40));
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 10));

        jButtonExit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Close-icon.png")); // NOI18N
        jButtonExit.setBorder(null);
        jButtonExit.setBorderPainted(false);
        jButtonExit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonExit.setFocusPainted(false);
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExitMouseClicked(evt);
            }
        });
        jPanel6.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 30, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 840, 60));

        jPanel2.setBackground(new java.awt.Color(31, 48, 93));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 255, 204));
        jTable1.setSelectionForeground(new java.awt.Color(51, 255, 204));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("Info");

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 320));

        jPanel3.setBackground(new java.awt.Color(31, 48, 93));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCreate.setBackground(new java.awt.Color(31, 48, 93));
        jButtonCreate.setForeground(new java.awt.Color(51, 255, 204));
        jButtonCreate.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Programming-Add-Property-icon.png")); // NOI18N
        jButtonCreate.setText("CREATE");
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jPanel3.add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, 40));

        jButtonDrop.setBackground(new java.awt.Color(31, 48, 93));
        jButtonDrop.setForeground(new java.awt.Color(51, 255, 204));
        jButtonDrop.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\database-delete-icon.png")); // NOI18N
        jButtonDrop.setText("DROP ");
        jButtonDrop.setPreferredSize(new java.awt.Dimension(115, 41));
        jButtonDrop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDropMouseClicked(evt);
            }
        });
        jPanel3.add(jButtonDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 40));

        jButtonUpdate.setBackground(new java.awt.Color(31, 48, 93));
        jButtonUpdate.setForeground(new java.awt.Color(51, 255, 204));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Actions-edit-redo-icon.png")); // NOI18N
        jButtonUpdate.setText("UPDATE");
        jPanel3.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, 40));

        jButtonEdit.setBackground(new java.awt.Color(31, 48, 93));
        jButtonEdit.setForeground(new java.awt.Color(51, 255, 204));
        jButtonEdit.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\fix-it-icon.png")); // NOI18N
        jButtonEdit.setText("EDIT");
        jButtonEdit.setPreferredSize(new java.awt.Dimension(115, 41));
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });
        jPanel3.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, -1));

        jButtonDone.setBackground(new java.awt.Color(31, 48, 93));
        jButtonDone.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Check-icon.png")); // NOI18N
        jButtonDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDoneMouseClicked(evt);
            }
        });
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 40));

        jTextArea1.setBackground(new Color(0,0,0,0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, 120));

        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Sql-runner-icon.png")); // NOI18N
        jLabel7.setText("TOOLS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 140, 50));

        jLabel8.setBackground(new Color(0,0,0,0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("String Query");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 255)));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 90, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, 410));

        jPanel4.setBackground(new java.awt.Color(31, 48, 93));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExport.setBackground(new java.awt.Color(31, 48, 93));
        jButtonExport.setForeground(new java.awt.Color(31, 48, 93));
        jButtonExport.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\export-icon.png")); // NOI18N
        jButtonExport.setBorder(null);
        jButtonExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExportMouseClicked(evt);
            }
        });
        jPanel4.add(jButtonExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 70, 80));

        jButtonScan.setBackground(new java.awt.Color(31, 48, 93));
        jButtonScan.setForeground(new java.awt.Color(31, 48, 93));
        jButtonScan.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Zoom-icon.png")); // NOI18N
        jButtonScan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonScanMouseClicked(evt);
            }
        });
        jPanel4.add(jButtonScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        jButtonPrint.setBackground(new java.awt.Color(31, 48, 93));
        jButtonPrint.setForeground(new java.awt.Color(31, 48, 93));
        jButtonPrint.setIcon(new javax.swing.ImageIcon("E:\\Java\\SQL-Tool\\lib\\icon\\Printer-Ink-icon.png")); // NOI18N
        jButtonPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrintMouseClicked(evt);
            }
        });
        jPanel4.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 70, 80));

        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("NameTB");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 30));

        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("NameDB");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, 30));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, 10));

        jTextFieldNameDB.setBackground(new java.awt.Color(31, 48, 93));
        jTextFieldNameDB.setFont(jTextFieldNameDB.getFont().deriveFont(jTextFieldNameDB.getFont().getSize()+5f));
        jTextFieldNameDB.setForeground(new java.awt.Color(51, 255, 204));
        jTextFieldNameDB.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNameDB.setAlignmentX(0.0F);
        jTextFieldNameDB.setAlignmentY(0.0F);
        jTextFieldNameDB.setBorder(null);
        jPanel4.add(jTextFieldNameDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 160, 30));

        jTextFieldNameTB.setBackground(new java.awt.Color(31, 48, 93));
        jTextFieldNameTB.setFont(jTextFieldNameTB.getFont().deriveFont(jTextFieldNameTB.getFont().getSize()+5f));
        jTextFieldNameTB.setForeground(new java.awt.Color(51, 255, 204));
        jTextFieldNameTB.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNameTB.setAlignmentX(0.0F);
        jTextFieldNameTB.setAlignmentY(0.0F);
        jTextFieldNameTB.setBorder(null);
        jPanel4.add(jTextFieldNameTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, 30));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 160, 10));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 500, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //xử lí sự kiện
    private void jButtonScanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonScanMouseClicked
        updateTable();
    }//GEN-LAST:event_jButtonScanMouseClicked

    private void jButtonExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExportMouseClicked
        String s1 = jTextFieldNameDB.getText();
        String s2 = jTextFieldNameTB.getText();
        if (s1.equals("") && (s2.equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Chưa điền thông tin!");
        }
        if (!s1.equals("") && (s2.equals(""))) {
            listIf = con.getInfoDB(s1);
            setTableTable();
            disPlayTableTb(listIf);
        }
        if ((!s1.equals("")) && (!s2.equals(""))) {
            try {
                link2Form("use "+s1+" select * from "+s2,"RETURN");
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_jButtonExportMouseClicked
    // in bang
    private void jButtonPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrintMouseClicked
        try {
            jTable1.print(JTable.PrintMode.NORMAL);
        } catch (PrinterException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonPrintMouseClicked

    private void jButtonDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDoneMouseClicked
        
        String s1 =jTextArea1.getText();
        if (s1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin điều không đúng!");
        } else {
            try {
                link2Form(s1,typeQuery(s1));
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButtonDoneMouseClicked

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        setLocation(x1 - x, y1 - y);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
       // System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(),jTable1.getSelectedColumn()));
    }//GEN-LAST:event_jButtonEditMouseClicked

    private void jButtonDropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDropMouseClicked
      dropDB();

    }//GEN-LAST:event_jButtonDropMouseClicked

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        callFormCreateDB();
    }//GEN-LAST:event_jButtonCreateMouseClicked


    
    //các hàm thêm vào
    public void updateTable(){
        setTableDB();
        listdb = con.getListNameDB();
        disPlayTableDB(listdb);
    }
    //----------------------------------------------------------------
    public void setTableDB() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "NAME", "ID"
                }
        ));
        model = (DefaultTableModel) jTable1.getModel();

    }
    public void setTableTable() {

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "NAMETB", "COLUMN_NAME", "DATA_TYPE", "MAX_LENGTH"
                }
        ));
        model = (DefaultTableModel) jTable1.getModel();
    }
    public void disPlayTableTb(ArrayList<InfoBasicDB> list) {
        model.setRowCount(0);
        for (InfoBasicDB inf : list) {
            model.addRow(inf.toArray());
        }
    }
    public void disPlayTableDB(ArrayList<DataBase> list) {

        model.setRowCount(0);
        for (DataBase inf : list) {
            model.addRow(inf.toArray());
        }
    }
    //---------------------------------------------------------------
    
    //thực hiện việc truyền tham số cho việc truy vấn
    public void link2Form(String sql, String typeSQL) throws SQLException {
        Controllerv2 m = new Controllerv2(sql, typeSQL);
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    // lọc câu truy ván xem nó thuộc kiểu nào : edit,update,select...
    public String typeQuery(String s){
        s=s.toLowerCase();
        if(s.contains("select")){
            return "RETURN";
        }
        return "NORETURN";
    }
    //gọi form tao db
    public void callFormCreateDB(){
        StringDB cdb = new StringDB();
        cdb.setVisible(true);
        cdb.pack();
        cdb.setLocationRelativeTo(null);
    }
    //lấy giá trị ô đang chọn
    public String getBoxTable(){
        String s="";
        int r = jTable1.getSelectedRow();
        int c = jTable1.getSelectedColumn();
        if (r != -1 && c != -1) {
            s = jTable1.getValueAt(r, c).toString();
        }
        return s;
    }
    //xóa database muốn xóa
    public void dropDB(){
        String s =getBoxTable();
        if (!s.equals("")) {
            int op = JOptionPane.showConfirmDialog(rootPane, "Ban có muốn xóa DB: " + s,
                    "CẢNH BÁO!", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                String sql = "drop database "+s; 
                try {
                    link2Form(s,"NORETURN");
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn tên DataBase để xóa!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JButton jButtonDrop;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonScan;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNameDB;
    private javax.swing.JTextField jTextFieldNameTB;
    // End of variables declaration//GEN-END:variables
}
